import { db } from "./db";
import { sendReminderEmail, sendBatchedReminderEmail } from "./email";
import { sendReminderSms, sendBatchedReminderSms } from "./sms";
import { differenceInDays, format, startOfDay, addDays } from "date-fns";
import {
  processEscalations,
  shouldSendReminder,
  getQuietHoursConfig,
  adjustForQuietHours,
  processAutoResumeReminders,
  getAllBatchedRemindersForDate,
  createBatchedReminder,
} from "./auto-reminder-scheduler";

/**
 * Process all scheduled reminders that are due to be sent
 * This handles both auto-generated reminders and legacy reminder configs
 */
export async function processReminders() {
  const today = startOfDay(new Date());
  const endOfDay = addDays(today, 1);

  // First, process any auto-resume for paused creators
  const resumedCount = await processAutoResumeReminders();
  if (resumedCount > 0) {
    console.log(`Auto-resumed reminders for ${resumedCount} creators`);
  }

  // Process auto-generated scheduled reminders first
  await processScheduledReminders(today, endOfDay);

  // Then process legacy reminder configs for backward compatibility
  await processLegacyReminders(today);
}

/**
 * Process auto-generated reminders that are scheduled for today
 * With support for quiet hours, batching, and response detection
 */
async function processScheduledReminders(today: Date, endOfDay: Date) {
  // Get all agencies with pending reminders
  const agencies = await db.contentRequest.findMany({
    where: {
      reminders: {
        some: {
          status: "PENDING",
          isAutoGenerated: true,
          scheduledAt: { gte: today, lt: endOfDay },
        },
      },
    },
    select: { agencyId: true },
    distinct: ["agencyId"],
  });

  // Process batched reminders first (multiple requests for same creator on same day)
  for (const { agencyId } of agencies) {
    const batches = await getAllBatchedRemindersForDate(agencyId, today);
    for (const batch of batches) {
      if (batch.requests.length >= 2) {
        await processBatchedReminder(batch, today);
      }
    }
  }

  // Get all remaining pending reminders scheduled for today
  const scheduledReminders = await db.reminder.findMany({
    where: {
      status: "PENDING",
      isAutoGenerated: true,
      isBatched: false, // Skip batched reminders (processed separately)
      scheduledAt: {
        gte: today,
        lt: endOfDay,
      },
    },
    include: {
      request: {
        include: {
          creator: true,
        },
      },
    },
  });

  console.log(`Processing ${scheduledReminders.length} individual scheduled reminders`);

  for (const reminder of scheduledReminders) {
    const { request } = reminder;

    // Skip if request is no longer in an active status
    if (!["PENDING", "IN_PROGRESS", "NEEDS_REVISION"].includes(request.status)) {
      await db.reminder.update({
        where: { id: reminder.id },
        data: { status: "SENT", sentAt: new Date(), error: "Request no longer active" },
      });
      continue;
    }

    // Check if reminder should be sent (pause status, quiet hours, recent activity)
    const sendCheck = await shouldSendReminder(
      request.id,
      request.creatorId,
      request.agencyId
    );

    if (!sendCheck.shouldSend) {
      console.log(`Skipping reminder ${reminder.id}: ${sendCheck.reason}`);

      // If it's quiet hours, reschedule for after quiet hours end
      if (sendCheck.reason?.includes("quiet hours")) {
        const quietHours = await getQuietHoursConfig(request.agencyId, request.creatorId);
        const { adjustedAt } = adjustForQuietHours(new Date(), quietHours);

        await db.reminder.update({
          where: { id: reminder.id },
          data: { scheduledAt: adjustedAt },
        });
        console.log(`Rescheduled reminder ${reminder.id} to ${adjustedAt.toISOString()}`);
      }
      continue;
    }

    const portalLink = `${process.env.APP_URL}/portal/${request.creator.id}/requests/${request.id}`;
    const dueDate = request.dueDate ? format(request.dueDate, "MMMM d, yyyy") : "Not set";
    const daysUntilDue = request.dueDate ? differenceInDays(request.dueDate, today) : 0;

    try {
      if (reminder.channel === "EMAIL") {
        await sendReminderEmail({
          to: request.creator.email,
          creatorName: request.creator.name,
          requestTitle: request.title,
          dueDate,
          daysUntilDue,
          portalLink,
        });
      } else if (reminder.channel === "SMS" && request.creator.phone) {
        await sendReminderSms({
          to: request.creator.phone,
          creatorName: request.creator.name,
          requestTitle: request.title,
          daysUntilDue,
          portalLink,
        });
      }

      await db.reminder.update({
        where: { id: reminder.id },
        data: { status: "SENT", sentAt: new Date() },
      });

      // Log the sent reminder
      await db.activityLog.create({
        data: {
          action: "reminder.sent",
          entityType: "Reminder",
          entityId: reminder.id,
          metadata: {
            requestId: request.id,
            creatorName: request.creator.name,
            type: reminder.type,
            channel: reminder.channel,
            isEscalation: reminder.isEscalation,
          },
        },
      });
    } catch (error) {
      console.error(`Failed to send reminder ${reminder.id}:`, error);
      await db.reminder.update({
        where: { id: reminder.id },
        data: {
          status: "FAILED",
          error: error instanceof Error ? error.message : "Unknown error",
        },
      });
    }
  }

  // Process escalations for overdue requests
  const overdueRequests = await db.contentRequest.findMany({
    where: {
      status: { in: ["PENDING", "IN_PROGRESS", "NEEDS_REVISION"] },
      dueDate: { lt: today },
    },
    select: { id: true },
  });

  for (const request of overdueRequests) {
    try {
      await processEscalations(request.id);
    } catch (error) {
      console.error(`Failed to process escalation for request ${request.id}:`, error);
    }
  }
}

/**
 * Process a batched reminder (multiple requests for same creator)
 */
async function processBatchedReminder(
  batch: Awaited<ReturnType<typeof getAllBatchedRemindersForDate>>[number],
  today: Date
) {
  // Check if reminder should be sent
  const sendCheck = await shouldSendReminder(
    batch.requests[0].id,
    batch.creatorId,
    "" // Will be resolved in shouldSendReminder
  );

  if (!sendCheck.shouldSend) {
    console.log(`Skipping batched reminder for ${batch.creatorName}: ${sendCheck.reason}`);
    return;
  }

  // Create a batched reminder record
  const batchedReminderId = await createBatchedReminder(batch);
  if (!batchedReminderId) return;

  const portalLink = `${process.env.APP_URL}/portal/${batch.creatorId}`;

  try {
    if (batch.channel === "EMAIL") {
      await sendBatchedReminderEmail({
        to: batch.creatorEmail,
        creatorName: batch.creatorName,
        requests: batch.requests.map((r) => ({
          title: r.title,
          dueDate: r.dueDate ? format(r.dueDate, "MMMM d, yyyy") : "No due date",
          daysUntilDue: r.daysFromDue,
          urgency: r.urgency,
        })),
        portalLink,
      });
    } else if (batch.channel === "SMS" && batch.creatorPhone) {
      await sendBatchedReminderSms({
        to: batch.creatorPhone,
        creatorName: batch.creatorName,
        requestCount: batch.requests.length,
        portalLink,
      });
    }

    await db.reminder.update({
      where: { id: batchedReminderId },
      data: { status: "SENT", sentAt: new Date() },
    });

    // Log the batched reminder
    await db.activityLog.create({
      data: {
        action: "reminder.batched_sent",
        entityType: "Reminder",
        entityId: batchedReminderId,
        metadata: {
          creatorId: batch.creatorId,
          creatorName: batch.creatorName,
          requestCount: batch.requests.length,
          requestIds: batch.requests.map((r) => r.id),
          channel: batch.channel,
        },
      },
    });

    console.log(
      `Sent batched reminder to ${batch.creatorName} for ${batch.requests.length} requests`
    );
  } catch (error) {
    console.error(`Failed to send batched reminder for ${batch.creatorName}:`, error);
    await db.reminder.update({
      where: { id: batchedReminderId },
      data: {
        status: "FAILED",
        error: error instanceof Error ? error.message : "Unknown error",
      },
    });
  }
}

/**
 * Process legacy reminder configs (ReminderConfig model)
 * For backward compatibility with agencies using the old system
 */
async function processLegacyReminders(today: Date) {
  // Get all agencies with their legacy reminder configs
  const agencies = await db.agency.findMany({
    include: {
      reminders: {
        where: { isActive: true },
      },
    },
  });

  for (const agency of agencies) {
    if (agency.reminders.length === 0) continue;

    const defaultConfig = agency.reminders[0];

    // Get pending requests that DON'T have auto-generated reminders
    // (to avoid double-sending)
    const requests = await db.contentRequest.findMany({
      where: {
        agencyId: agency.id,
        status: { in: ["PENDING", "IN_PROGRESS", "NEEDS_REVISION"] },
        dueDate: { not: null },
        reminders: {
          none: {
            isAutoGenerated: true,
          },
        },
      },
      include: {
        creator: true,
        reminders: {
          where: {
            scheduledAt: {
              gte: startOfDay(today),
              lt: addDays(today, 1),
            },
          },
        },
      },
    });

    for (const request of requests) {
      if (!request.dueDate) continue;

      const daysUntilDue = differenceInDays(request.dueDate, today);

      // Check if we should send a reminder today
      const shouldRemind =
        defaultConfig.daysBefore.includes(daysUntilDue) ||
        (daysUntilDue < 0 &&
          defaultConfig.escalateDaysOverdue &&
          Math.abs(daysUntilDue) % defaultConfig.escalateDaysOverdue === 0);

      if (!shouldRemind) continue;

      // Check if reminder already sent today
      const existingReminder = request.reminders.find(
        (r) => r.status === "SENT"
      );
      if (existingReminder) continue;

      // Determine reminder type
      let reminderType: "UPCOMING" | "DUE_TODAY" | "OVERDUE" | "ESCALATION";
      if (daysUntilDue > 0) {
        reminderType = "UPCOMING";
      } else if (daysUntilDue === 0) {
        reminderType = "DUE_TODAY";
      } else if (
        defaultConfig.escalateDaysOverdue &&
        Math.abs(daysUntilDue) >= defaultConfig.escalateDaysOverdue
      ) {
        reminderType = "ESCALATION";
      } else {
        reminderType = "OVERDUE";
      }

      const portalLink = `${process.env.APP_URL}/portal/${request.creator.id}/requests/${request.id}`;
      const dueDate = format(request.dueDate, "MMMM d, yyyy");

      // Send email reminder
      if (defaultConfig.sendEmail) {
        const reminder = await db.reminder.create({
          data: {
            requestId: request.id,
            type: reminderType,
            channel: "EMAIL",
            scheduledAt: new Date(),
            isAutoGenerated: false, // Mark as legacy
          },
        });

        try {
          await sendReminderEmail({
            to: request.creator.email,
            creatorName: request.creator.name,
            requestTitle: request.title,
            dueDate,
            daysUntilDue,
            portalLink,
          });

          await db.reminder.update({
            where: { id: reminder.id },
            data: { status: "SENT", sentAt: new Date() },
          });
        } catch (error) {
          console.error("Failed to send reminder email:", error);
          await db.reminder.update({
            where: { id: reminder.id },
            data: {
              status: "FAILED",
              error: error instanceof Error ? error.message : "Unknown error",
            },
          });
        }
      }

      // Send SMS reminder
      if (
        defaultConfig.sendSms &&
        request.creator.phone &&
        (request.creator.preferredContact === "SMS" ||
          request.creator.preferredContact === "BOTH")
      ) {
        const reminder = await db.reminder.create({
          data: {
            requestId: request.id,
            type: reminderType,
            channel: "SMS",
            scheduledAt: new Date(),
            isAutoGenerated: false, // Mark as legacy
          },
        });

        try {
          await sendReminderSms({
            to: request.creator.phone,
            creatorName: request.creator.name,
            requestTitle: request.title,
            daysUntilDue,
            portalLink,
          });

          await db.reminder.update({
            where: { id: reminder.id },
            data: { status: "SENT", sentAt: new Date() },
          });
        } catch (error) {
          console.error("Failed to send reminder SMS:", error);
          await db.reminder.update({
            where: { id: reminder.id },
            data: {
              status: "FAILED",
              error: error instanceof Error ? error.message : "Unknown error",
            },
          });
        }
      }
    }
  }
}

// Function to be called by a cron job (e.g., Vercel Cron)
export async function runReminderCron() {
  console.log("Running reminder cron job...");

  try {
    await processReminders();
    console.log("Reminder cron job completed successfully");
    return { success: true };
  } catch (error) {
    console.error("Reminder cron job failed:", error);
    return { success: false, error };
  }
}
