import { NextRequest, NextResponse } from "next/server";
import { getServerSession } from "next-auth";
import { authOptions } from "@/lib/auth";
import { db } from "@/lib/db";
import { z } from "zod";
import {
  scheduleRemindersForRequest,
  previewReminderSchedule,
  cancelAutoGeneratedReminders,
  getRemindersummary,
} from "@/lib/auto-reminder-scheduler";

// ============================================
// VALIDATION SCHEMAS
// ============================================

const scheduleOptionsSchema = z.object({
  preview: z.boolean().default(false),
  cancelExisting: z.boolean().default(true),
});

// ============================================
// GET - Get reminder summary and preview for a request
// ============================================

export async function GET(
  req: NextRequest,
  { params }: { params: Promise<{ id: string }> }
) {
  try {
    const session = await getServerSession(authOptions);
    const { id: requestId } = await params;

    if (!session?.user?.agencyId) {
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
    }

    // Verify request belongs to agency
    const request = await db.contentRequest.findFirst({
      where: {
        id: requestId,
        agencyId: session.user.agencyId,
      },
      include: {
        creator: {
          select: {
            id: true,
            name: true,
            preferredContact: true,
          },
        },
      },
    });

    if (!request) {
      return NextResponse.json(
        { error: "Request not found" },
        { status: 404 }
      );
    }

    // Get current reminder summary
    const summary = await getRemindersummary(requestId);

    // Get preview of what reminders would be scheduled
    let preview = null;
    if (request.dueDate) {
      preview = await previewReminderSchedule(requestId);
    }

    return NextResponse.json({
      requestId,
      creator: request.creator,
      dueDate: request.dueDate,
      urgency: request.urgency,
      status: request.status,
      summary,
      preview,
    });
  } catch (error) {
    console.error("Error fetching reminder info:", error);
    return NextResponse.json(
      { error: "Failed to fetch reminder information" },
      { status: 500 }
    );
  }
}

// ============================================
// POST - Schedule or reschedule reminders for a request
// ============================================

export async function POST(
  req: NextRequest,
  { params }: { params: Promise<{ id: string }> }
) {
  try {
    const session = await getServerSession(authOptions);
    const { id: requestId } = await params;

    if (!session?.user?.agencyId) {
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
    }

    // Verify request belongs to agency
    const request = await db.contentRequest.findFirst({
      where: {
        id: requestId,
        agencyId: session.user.agencyId,
      },
      include: {
        creator: {
          select: {
            id: true,
            name: true,
          },
        },
      },
    });

    if (!request) {
      return NextResponse.json(
        { error: "Request not found" },
        { status: 404 }
      );
    }

    // Check if request has a due date
    if (!request.dueDate) {
      return NextResponse.json(
        { error: "Cannot schedule reminders for a request without a due date" },
        { status: 400 }
      );
    }

    // Check if request is in a valid status for reminders
    const validStatuses = ["PENDING", "IN_PROGRESS", "NEEDS_REVISION"];
    if (!validStatuses.includes(request.status)) {
      return NextResponse.json(
        {
          error: `Cannot schedule reminders for a request with status: ${request.status}`,
        },
        { status: 400 }
      );
    }

    // Parse options from body
    const body = await req.json().catch(() => ({}));
    const options = scheduleOptionsSchema.parse(body);

    // If preview mode, just return what would be scheduled
    if (options.preview) {
      const preview = await previewReminderSchedule(requestId);
      return NextResponse.json({
        preview: true,
        ...preview,
      });
    }

    // Schedule reminders
    const result = await scheduleRemindersForRequest(requestId, {
      preview: false,
      cancelExisting: options.cancelExisting,
    });

    // Log activity
    await db.activityLog.create({
      data: {
        userId: session.user.id,
        action: "reminders.manually_scheduled",
        entityType: "ContentRequest",
        entityId: requestId,
        metadata: {
          remindersCreated: result.remindersCreated,
          configSource: result.config.source,
          creatorName: request.creator.name,
        },
      },
    });

    return NextResponse.json({
      message: `${result.remindersCreated} reminders scheduled successfully`,
      ...result,
    });
  } catch (error) {
    if (error instanceof z.ZodError) {
      return NextResponse.json(
        { error: error.issues[0].message },
        { status: 400 }
      );
    }

    console.error("Error scheduling reminders:", error);
    return NextResponse.json(
      { error: "Failed to schedule reminders" },
      { status: 500 }
    );
  }
}

// ============================================
// DELETE - Cancel all auto-generated reminders for a request
// ============================================

export async function DELETE(
  req: NextRequest,
  { params }: { params: Promise<{ id: string }> }
) {
  try {
    const session = await getServerSession(authOptions);
    const { id: requestId } = await params;

    if (!session?.user?.agencyId) {
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
    }

    // Verify request belongs to agency
    const request = await db.contentRequest.findFirst({
      where: {
        id: requestId,
        agencyId: session.user.agencyId,
      },
      include: {
        creator: {
          select: {
            name: true,
          },
        },
      },
    });

    if (!request) {
      return NextResponse.json(
        { error: "Request not found" },
        { status: 404 }
      );
    }

    // Cancel auto-generated reminders
    const cancelledCount = await cancelAutoGeneratedReminders(requestId);

    // Log activity
    await db.activityLog.create({
      data: {
        userId: session.user.id,
        action: "reminders.cancelled",
        entityType: "ContentRequest",
        entityId: requestId,
        metadata: {
          cancelledCount,
          creatorName: request.creator.name,
        },
      },
    });

    return NextResponse.json({
      message: `${cancelledCount} auto-generated reminders cancelled`,
      cancelledCount,
    });
  } catch (error) {
    console.error("Error cancelling reminders:", error);
    return NextResponse.json(
      { error: "Failed to cancel reminders" },
      { status: 500 }
    );
  }
}
